### ISSUE TITLE
no monospace font

### ISSUE THREAD

**Issue by setanarut** [GodotDocMobile/godot_class_reference#7] opened 2022-03-09 21:01 UTC
keywords method names etc. It should be a monospace font.

**Comment by fengjiongmax** [comment] 2022-03-10 19:55
> keywords method names etc. It should be a monospace font.

I guess that means link text, they are now rendered with a monospaced font.
![Screenshot_1646941830_rect](https://user-images.githubusercontent.com/5288733/157744051-0c6e5300-45d0-4d58-86cb-78b3c1cee9c8.png)

**Comment by setanarut** [comment] 2022-03-10 20:29
version 0.3.4 no monospace for me.  

![mono](https://user-images.githubusercontent.com/36481442/157749099-de4250bd-2bd2-4770-b43c-658c8a321d19.jpg)

**Comment by fengjiongmax** [comment] 2022-03-10 22:04
Oh, my bad :sweat_smile:  , I forgot to say those should render with monospace font with commit 95901f452e513440086610e18bb7ad20097f7c54 .
And I'm not sure if we should make the class list (the main screen) rendered with monospace.
After a bit of research, I'm not even sure if we should render text with monospace font outside of in-line code or codeblock, as rendering with monospace may reduce readability, and make them harder to read.

**Comment by setanarut** [comment] 2022-03-11 08:51
> Oh, my bad 😅 , I forgot to say those should render with monospace font with commit [95901f4](https://github.com/GodotDocMobile/godot_class_reference/commit/95901f452e513440086610e18bb7ad20097f7c54) . And I'm not sure if we should make the class list (the main screen) rendered with monospace. After a bit of research, I'm not even sure if we should render text with monospace font outside of in-line code or codeblock, as rendering with monospace may reduce readability, and make them harder to read.

all class names, members, method names..etc are codes. Mono fonts are more readable than plain fonts for important keywords. you can make an option in app settings. I suggest jetbrains mono font. https://www.jetbrains.com/lp/mono/#:~:text=In%20JetBrains%20IDEs,-The%20most%20recent&text=Select%20JetBrains%20Mono%20in%20the,Mono%20from%20the%20Font%20dropdown. Godot 4 uses this font.

**Comment by fengjiongmax** [comment] 2022-03-11 10:52
OK, an option for monospaced font (using jetbrains mono) will be added.
![Screenshot_1646995944](https://user-images.githubusercontent.com/5288733/157853557-385c5cf5-cea1-4e66-9885-25c58843c27f.png)

**Comment by fengjiongmax** [comment] 2022-03-11 11:48
Changes will be released under version 0.3.5, should be available in a day or two.

**Comment by setanarut** [comment] 2022-03-11 11:52
> Changes will be released under version 0.3.5, should be available in a day or two.

which changes. any screenshot? yellow parts on my screenshot or only red parts on your screenshot?

**Comment by fengjiongmax** [comment] 2022-03-11 12:11
After the 'monospace font' switch is on:
![Screenshot_1647000504](https://user-images.githubusercontent.com/5288733/157864492-e8aa4bbd-5731-4ea4-9f3a-a78c7df16ec8.png)
![Screenshot_1647000515](https://user-images.githubusercontent.com/5288733/157864499-ed04fdee-898a-44d8-8c7b-b26bd0c5ab52.png)
![Screenshot_1647000518](https://user-images.githubusercontent.com/5288733/157864509-d936fec4-f0e7-4a93-ae14-806d12dffaff.png)
![Screenshot_1647000520](https://user-images.githubusercontent.com/5288733/157864565-f2d7f0a1-c146-44ae-aca2-f72ec5e1c124.png)
![Screenshot_1647000522](https://user-images.githubusercontent.com/5288733/157864587-bb58656c-044b-489d-b17f-025133c1a1e4.png)
![Screenshot_1647000524](https://user-images.githubusercontent.com/5288733/157864594-78316015-421a-4928-9c26-9161530ae046.png)
![Screenshot_1647000527](https://user-images.githubusercontent.com/5288733/157864600-6ec25349-7ac4-4073-bafe-942b41c2046c.png)

**Comment by setanarut** [comment] 2022-03-11 12:21
thanks excellent. good job

**Comment by setanarut** [comment] 2022-03-12 12:07
hi. Version 0.3.5. Monospace option doesn't work.

**Comment by fengjiongmax** [comment] 2022-03-12 12:28
This seems to be caused by the google font package: https://stackoverflow.com/a/59491170/5228489
The workaround is to embed the font into the app, I'll make sure it works before releasing the app. :stuck_out_tongue:

**Comment by fengjiongmax** [comment] 2022-03-12 12:48
This should be fixed with commit 7dc3791ac88833f0dbe89c90def3a3b601972072

**Comment by fengjiongmax** [comment] 2022-03-12 13:17
Edit:
I've tested on several devices, the patch seems to work, and will be released under version 0.3.6.

**Closed as completed** 2022-03-14 10:39 UTC
Labels: enhancement
